### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by jmichelin** [breakfast-mimes/cyber-mimes#105]
node app/web/server.js

**Comment by jmichelin** [comment]
npm run server

> cyber-mimes@1.0.0 server /Users/jmichelin/makersquare/mks46/mimes/cyber-mimes/cyber-mimes
> babel-node server.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/jmichelin/makersquare/mks46/mimes/cyber-mimes/cyber-mimes/server.js'

**Comment by selimc** [comment]
Whats the error message for 'npm start' ?
